#ifndef _H_TLIBC_ERROR_CODE
#define _H_TLIBC_ERROR_CODE

#include "tlibc/platform/tlibc_platform.h"

typedef enum _TLIBC_ERROR_CODE
{
    E_TLIBC_NOERROR = 0,
    E_TLIBC_ERROR = -1,	
    E_TLIBC_OUT_OF_MEMORY = -2,
	E_TLIBC_NOT_FOUND = -3,
	E_TLIBC_SYNTAX = -4,
	E_TLIBC_MISMATCH = -5,
	E_TLIBC_ERRNO = -6,
	E_TLIBC_WOULD_BLOCK = -7,
	E_TLIBC_BAD_FILE = -8,
	E_TLIBC_EOF = -9,	
	E_TLIBC_EMPTY = -10,
	E_TLIBC_PLEASE_READ_ENUM_NAME = -11,
	E_TLIBC_INTEGER_OVERFLOW = 12,
	E_TLIBC_IGNORE = 13,
}TLIBC_ERROR_CODE;

#define TLIBC_ERROR_CODE_NUM 15

#endif
