/**
 * Autogenerated by TData Compiler (0.0.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

#ifndef _H_TDATA_TDATA_TYPES_H
#define _H_TDATA_TDATA_TYPES_H

#include "platform/tlibc_platform.h"



#define TLIBC_MAX_IDENTIFIER_LENGTH 128

#endif //_H_TDATA_TDATA_TYPES_H

